In [21]:
# NYC Jobs Salary Analysis Project
## Project Overview:
## This project explores NYC government job postings to analyze salary ranges, hiring trends, and job requirements. 
## The dataset is cleaned using Python (pandas) before being analyzed further with SQL and visualizations.

In [22]:
## Data Cleaning

In [23]:
# Import the pandas library for data manipulation and analysi
import pandas as pd

print(pd.__version__)

3.0.3

In [24]:
# Load the raw NYC Jobs dataset into a DataFrame
jobs = pd.read_csv("Jobs_NYC_Postings.csv")
# Display the first five rows to verify the dataset loaded correctly
jobs.head()

,Job ID,Agency,Posting Type,# Of Positions,Business Title,Civil Service Title,Title Classification,Title Code No,Level,Job Category,...,Additional Information,To Apply,Hours/Shift,Work Location 1,Recruitment Contact,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
0,780282,DISTRICT ATTORNEY RICHMOND COU,Internal,1,Victim Advocate,COMMUNITY ASSOCIATE,Non-Competitive-5,56057,00,Social Services,...,NaN,TO APPLY: ALL APPLICATIONS MUST BE SUBMITTED T...,NaN,"130 Stuyvesant Place, S.I.",NaN,New York City residency is generally required ...,07/10/2026,08-SEP-2026,07/10/2026,07/20/2026
1,786162,OFFICE OF CRIMINAL JUSTICE,External,1,"Lead Researcher, Behavioral Health",RESEARCH PROJECTS COOR(MA)-MGR,Pending Classification-2,0527A,M1,"Technology, Data & Innovation",...,NaN,NaN,NaN,"1 Centre St., N.Y.",NaN,New York City residency is generally required ...,07/14/2026,12-SEP-2026,07/15/2026,07/20/2026
2,783706,POLICE DEPARTMENT,External,1,"Instructor, Civilian Development Unit",ADM MANAGER-NON-MGRL FRM M1/M2,Competitive-1,1002C,01,"Policy, Research & Analysis",...,All instructors in the NYPD Police Academy mus...,"Click the ‘Apply’ Button below, or visit: http...","Day Tours: Monday Through Friday, Saturday and...",130-30 28th Ave,NaN,New York City residency is generally required ...,06/22/2026,22-JUL-2026,07/09/2026,07/20/2026
3,782778,CONSUMER AND WORKER PROTECTION,External,2,Litigation Supervisor - Worker Protection,EXECUTIVE AGENCY COUNSEL,Non-Competitive-5,95005,M5,Legal Affairs,...,"In addition, the NYC Department of Consumer an...","To apply for this position, please submit your...",NaN,"42 Broadway, N.Y.",NaN,New York City Residency is not required for th...,06/08/2026,07-AUG-2026,06/08/2026,07/20/2026
4,786621,CONSUMER AND WORKER PROTECTION,External,1,Business Analyst / Project Manager,COMPUTER SYSTEMS MANAGER,Competitive-1,1005D,00,"Technology, Data & Innovation",...,"In addition, the NYC Department of Consumer an...","To apply for this position, please submit your...",NaN,"42 Broadway, N.Y.",NaN,New York City Residency is not required for th...,07/16/2026,14-SEP-2026,07/17/2026,07/20/2026

In [25]:
# Check the number of rows and columns in the dataset
jobs.shape

(2376, 30)

In [26]:
# Inspect column names, data types, and missing values
jobs.info()

<class 'pandas.DataFrame'>
RangeIndex: 2376 entries, 0 to 2375
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Job ID                         2376 non-null   int64
 1   Agency                         2376 non-null   str
 2   Posting Type                   2376 non-null   str
 3   # Of Positions                 2376 non-null   int64
 4   Business Title                 2376 non-null   str
 5   Civil Service Title            2376 non-null   str
 6   Title Classification           2376 non-null   str
 7   Title Code No                  2376 non-null   str
 8   Level                          2376 non-null   str
 9   Job Category                   2376 non-null   str
 10  Full-Time/Part-Time indicator  2376 non-null   str
 11  Career Level                   2376 non-null   str
 12  Salary Range From              2376 non-null   float64
 13  Salary Range To                2376 non-null   float64
 14  Salary Frequency               2376 non-null   str
 15  Work Location                  2376 non-null   str
 16  Division/Work Unit             2376 non-null   str
 17  Job Description                2376 non-null   str
 18  Minimum Qual Requirements      2340 non-null   str
 19  Preferred Skills               1273 non-null   str
 20  Additional Information         732 non-null    str
 21  To Apply                       1003 non-null   str
 22  Hours/Shift                    300 non-null    str
 23  Work Location 1                2376 non-null   str
 24  Recruitment Contact            0 non-null      float64
 25  Residency Requirement          2376 non-null   str
 26  Posting Date                   2376 non-null   str
 27  Post Until                     2327 non-null   str
 28  Posting Updated                2376 non-null   str
 29  Process Date                   2376 non-null   str
dtypes: float64(3), int64(2), str(25)
memory usage: 557.0 KB

In [27]:
# Generate summary statistics for numerical columns
jobs.describe()

,Job ID,# Of Positions,Salary Range From,Salary Range To,Recruitment Contact
count,2376.000000,2376.000000,2376.00000,2376.00000,0.0
mean,777575.143939,2.165825,74108.62890,96282.18712,NaN
std,17823.459838,8.666321,35147.38966,46981.32875,NaN
min,540190.000000,1.000000,0.00000,18.00000,NaN
25%,779240.000000,1.000000,59747.00000,70904.00000,NaN
50%,783133.500000,1.000000,70000.00000,92657.00000,NaN
75%,784526.750000,1.000000,87743.00000,117000.00000,NaN
max,787069.000000,243.000000,250000.00000,277671.00000,NaN

In [28]:
# Count missing values in each column
jobs.isnull().sum().sort_values(ascending=False)

Recruitment Contact              2376
Hours/Shift                      2076
Additional Information           1644
To Apply                         1373
Preferred Skills                 1103
Post Until                         49
Minimum Qual Requirements          36
Title Classification                0
Job ID                              0
Agency                              0
Posting Type                        0
# Of Positions                      0
Business Title                      0
Civil Service Title                 0
Salary Range To                     0
Salary Range From                   0
Career Level                        0
Full-Time/Part-Time indicator       0
Job Category                        0
Level                               0
Title Code No                       0
Job Description                     0
Salary Frequency                    0
Work Location                       0
Division/Work Unit                  0
Work Location 1                     0
Residency Requirement               0
Posting Date                        0
Posting Updated                     0
Process Date                        0
dtype: int64

In [29]:
# Count the number of duplicate rows
jobs.duplicated().sum()

np.int64(14)

In [30]:
# Display all duplicate rows for inspection
duplicates = jobs[jobs.duplicated(keep=False)]
duplicates

,Job ID,Agency,Posting Type,# Of Positions,Business Title,Civil Service Title,Title Classification,Title Code No,Level,Job Category,...,Additional Information,To Apply,Hours/Shift,Work Location 1,Recruitment Contact,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
33,785168,NYC POLICE PENSION FUND,Internal,1,Retirement Processing Help Desk Liaison,CUSTOMER INFORMATION REP,Competitive-1,60888,01,Administration & Human Resources,...,NOTE: This is a full-time on-site position whe...,Go to https://cityjobs.nyc.gov and search for ...,8:30AM – 4:30PM,233 Broadway,NaN,New York City residency is generally required ...,07/16/2026,29-JUL-2026,07/16/2026,07/20/2026
34,785168,NYC POLICE PENSION FUND,Internal,1,Retirement Processing Help Desk Liaison,CUSTOMER INFORMATION REP,Competitive-1,60888,01,Administration & Human Resources,...,NOTE: This is a full-time on-site position whe...,Go to https://cityjobs.nyc.gov and search for ...,8:30AM – 4:30PM,233 Broadway,NaN,New York City residency is generally required ...,07/16/2026,29-JUL-2026,07/16/2026,07/20/2026
428,779708,DEPT OF HEALTH/MENTAL HYGIENE,Internal,2,"Scientist (Water Ecology), Bureau of Environme...",SCIENTIST (WATER ECOLOGY),Competitive-1,21538,02,"Public Safety, Inspections, & Enforcement",...,NaN,NaN,NaN,NYC - All Boroughs,NaN,New York City residency is generally required ...,05/27/2026,26-JUL-2026,05/27/2026,07/20/2026
429,779708,DEPT OF HEALTH/MENTAL HYGIENE,Internal,2,"Scientist (Water Ecology), Bureau of Environme...",SCIENTIST (WATER ECOLOGY),Competitive-1,21538,02,"Public Safety, Inspections, & Enforcement",...,NaN,NaN,NaN,NYC - All Boroughs,NaN,New York City residency is generally required ...,05/27/2026,26-JUL-2026,05/27/2026,07/20/2026
449,782414,OFFICE OF THE COMPTROLLER,External,2,Litigation Attorney,AGENCY ATTORNEY,Non-Competitive-5,30087,01,Legal Affairs,...,NaN,NaN,NaN,"1 Centre St., N.Y.",NaN,New York City Residency is not required for th...,06/02/2026,01-AUG-2026,06/02/2026,07/20/2026
450,782414,OFFICE OF THE COMPTROLLER,External,2,Litigation Attorney,AGENCY ATTORNEY,Non-Competitive-5,30087,01,Legal Affairs,...,NaN,NaN,NaN,"1 Centre St., N.Y.",NaN,New York City Residency is not required for th...,06/02/2026,01-AUG-2026,06/02/2026,07/20/2026
556,785842,NYC HOUSING AUTHORITY,Internal,1,SUPERVISOR OF HOUSING CARETAKER (HA),SUPERVISOR OF HOUSING CARETAKE,Competitive-1,82011,00,Building Operations & Maintenance,...,1.\tFor NYCHA employees. this position is open...,"Click the ""Apply Now"" button.",NaN,Pomonok,NaN,NYCHA has no residency requirements.,07/16/2026,26-JUL-2026,07/16/2026,07/20/2026
557,785842,NYC HOUSING AUTHORITY,Internal,1,SUPERVISOR OF HOUSING CARETAKER (HA),SUPERVISOR OF HOUSING CARETAKE,Competitive-1,82011,00,Building Operations & Maintenance,...,1.\tFor NYCHA employees. this position is open...,"Click the ""Apply Now"" button.",NaN,Pomonok,NaN,NYCHA has no residency requirements.,07/16/2026,26-JUL-2026,07/16/2026,07/20/2026
658,783313,DEPT OF HEALTH/MENTAL HYGIENE,External,1,"Deputy Commissioner/Chief Equity Officer, Cent...",DEPUTY COMMISSIONER (MENTAL HE,Exempt-4,95477,M6,Health,...,NaN,NaN,NaN,42-09 28th Street,NaN,New York City residency is generally required ...,06/12/2026,11-AUG-2026,06/26/2026,07/20/2026
659,783313,DEPT OF HEALTH/MENTAL HYGIENE,External,1,"Deputy Commissioner/Chief Equity Officer, Cent...",DEPUTY COMMISSIONER (MENTAL HE,Exempt-4,95477,M6,Health,...,NaN,NaN,NaN,42-09 28th Street,NaN,New York City residency is generally required ...,06/12/2026,11-AUG-2026,06/26/2026,07/20/2026
695,783313,DEPT OF HEALTH/MENTAL HYGIENE,Internal,1,"Deputy Commissioner/Chief Equity Officer, Cent...",DEPUTY COMMISSIONER (MENTAL HE,Exempt-4,95477,M6,Health,...,NaN,NaN,NaN,42-09 28th Street,NaN,New York City residency is generally required ...,06/12/2026,11-AUG-2026,06/26/2026,07/20/2026
696,783313,DEPT OF HEALTH/MENTAL HYGIENE,Internal,1,"Deputy Commissioner/Chief Equity Officer, Cent...",DEPUTY COMMISSIONER (MENTAL HE,Exempt-4,95477,M6,Health,...,NaN,NaN,NaN,42-09 28th Street,NaN,New York City residency is generally required ...,06/12/2026,11-AUG-2026,06/26/2026,07/20/2026
1288,786420,NYC POLICE PENSION FUND,Internal,1,Retirement Processor,COMMUNITY ASSOCIATE,Non-Competitive-5,56057,00,Administration & Human Resources,...,NOTE: This is a full-time on-site position whe...,Go to https://cityjobs.nyc.gov and search for ...,9:30AM – 5:30PM,233 Broadway,NaN,New York City residency is generally required ...,07/20/2026,02-AUG-2026,07/20/2026,07/20/2026
1289,786420,NYC POLICE PENSION FUND,Internal,1,Retirement Processor,COMMUNITY ASSOCIATE,Non-Competitive-5,56057,00,Administration & Human Resources,...,NOTE: This is a full-time on-site position whe...,Go to https://cityjobs.nyc.gov and search for ...,9:30AM – 5:30PM,233 Broadway,NaN,New York City residency is generally required ...,07/20/2026,02-AUG-2026,07/20/2026,07/20/2026
1495,784715,DEPT OF ENVIRONMENT PROTECTION,Internal,1,Appeal Group,PRINCIPAL ADMINISTRATIVE ASSOC,Competitive-1,10124,02,Constituent Services & Community Programs,...,NaN,NaN,NaN,59-17 Junction Blvd Corona Ny,NaN,New York City residency is generally required ...,07/06/2026,04-SEP-2026,07/07/2026,07/20/2026
1496,784715,DEPT OF ENVIRONMENT PROTECTION,Internal,1,Appeal Group,PRINCIPAL ADMINISTRATIVE ASSOC,Competitive-1,10124,02,Constituent Services & Community Programs,...,NaN,NaN,NaN,59-17 Junction Blvd Corona Ny,NaN,New York City residency is generally required ...,07/06/2026,04-SEP-2026,07/07/2026,07/20/2026
1585,779708,DEPT OF HEALTH/MENTAL HYGIENE,External,2,"Scientist (Water Ecology), Bureau of Environme...",SCIENTIST (WATER ECOLOGY),Competitive-1,21538,02,"Public Safety, Inspections, & Enforcement",...,NaN,NaN,NaN,NYC - All Boroughs,NaN,New York City residency is generally required ...,05/27/2026,26-JUL-2026,05/27/2026,07/20/2026
1586,779708,DEPT OF HEALTH/MENTAL HYGIENE,External,2,"Scientist (Water Ecology), Bureau of Environme...",SCIENTIST (WATER ECOLOGY),Competitive-1,21538,02,"Public Safety, Inspections, & Enforcement",...,NaN,NaN,NaN,NYC - All Boroughs,NaN,New York City residency is generally required ...,05/27/2026,26-JUL-2026,05/27/2026,07/20/2026
1690,762686,DISTRICT ATTORNEY-MANHATTAN,External,1,HR Manager,EXECUTIVE DIRECTOR (PERSONNEL),Non-Competitive-5,94606,M1,Administration & Human Resources,...,NaN,NaN,NaN,"40 Worth St., N.Y.",NaN,•\tCity Residency is not required for this pos...,07/09/2026,07-SEP-2026,07/09/2026,07/20/2026
1691,762686,DISTRICT ATTORNEY-MANHATTAN,External,1,HR Manager,EXECUTIVE DIRECTOR (PERSONNEL),Non-Competitive-5,94606,M1,Administration & Human Resources,...,NaN,NaN,NaN,"40 Worth St., N.Y.",NaN,•\tCity Residency is not required for this pos...,07/09/2026,07-SEP-2026,07/09/2026,07/20/2026
1727,785546,HRA/DEPT OF SOCIAL SERVICES,Internal,1,Customer Care Representative,CLERICAL ASSOCIATE,Competitive-1,10251,04,Administration & Human Resources,...,"In addition, the Human Resources Administratio...",CLICK “APPLY NOW” BUTTON,NaN,4 World Trade Center,NaN,New York City residency is generally required ...,07/09/2026,07-SEP-2026,07/13/2026,07/20/2026
1728,785546,HRA/DEPT OF SOCIAL SERVICES,Internal,1,Customer Care Representative,CLERICAL ASSOCIATE,Competitive-1,10251,04,Administration & Human Resources,...,"In addition, the Human Resources Administratio...",CLICK “APPLY NOW” BUTTON,NaN,4 World Trade Center,NaN,New York City residency is generally required ...,07/09/2026,07-SEP-2026,07/13/2026,07/20/2026
2075,777685,DEPT OF ENVIRONMENT PROTECTION,Internal,1,Assistant EHS Management System (MS) Data Coor...,CITY RESEARCH SCIENTIST,Non-Competitive-5,21744,01,"Health Policy, Research & Analysis",...,NaN,"Press the ""apply now"" button.",Monday - Friday 35 hours per week,59-17 Junction Blvd Corona Ny,NaN,New York City residency is generally required ...,05/27/2026,26-JUL-2026,05/27/2026,07/20/2026
2076,777685,DEPT OF ENVIRONMENT PROTECTION,Internal,1,Assistant EHS Management System (MS) Data Coor...,CITY RESEARCH SCIENTIST,Non-Competitive-5,21744,01,"Health Policy, Research & Analysis",...,NaN,"Press the ""apply now"" button.",Monday - Friday 35 hours per week,59-17 Junction Blvd Corona Ny,NaN,New York City residency is generally required ...,05/27/2026,26-JUL-2026,05/27/2026,07/20/2026
2193,785842,NYC HOUSING AUTHORITY,External,1,SUPERVISOR OF HOUSING CARETAKER (HA),SUPERVISOR OF HOUSING CARETAKE,Competitive-1,82011,00,Building Operations & Maintenance,...,1.\tFor NYCHA employees. this position is open...,"Click the ""Apply Now"" button.",NaN,Pomonok,NaN,NYCHA has no residency requirements.,07/16/2026,26-JUL-2026,07/16/2026,07/20/2026
2194,785842,NYC HOUSING AUTHORITY,External,1,SUPERVISOR OF HOUSING CARETAKER (HA),SUPERVISOR OF HOUSING CARETAKE,Competitive-1,82011,00,Building Operations & Maintenance,...,1.\tFor NYCHA employees. this position is open...,"Click the ""Apply Now"" button.",NaN,Pomonok,NaN,NYCHA has no residency requirements.,07/16/2026,26-JUL-2026,07/16/2026,07/20/2026
2209,781842,DEPT OF ENVIRONMENT PROTECTION,External,1,Machinist,MACHINIST,Competitive-1,92610,00,Building Operations & Maintenance,...,NaN,In-city Employees: Log on to nyc.gov/jobs and ...,NaN,"465 Columbus Ave. Valhalla, Ny",NaN,New York City Residency is not required for th...,07/10/2026,23-AUG-2026,07/10/2026,07/20/2026
2210,781842,DEPT OF ENVIRONMENT PROTECTION,External,1,Machinist,MACHINIST,Competitive-1,92610,00,Building Operations & Maintenance,...,NaN,In-city Employees: Log on to nyc.gov/jobs and ...,NaN,"465 Columbus Ave. Valhalla, Ny",NaN,New York City Residency is not required for th...,07/10/2026,23-AUG-2026,07/10/2026,07/20/2026

In [31]:
# Generate summary statistics for all categorical (text) columns
jobs.describe(include="str")

,Agency,Posting Type,Business Title,Civil Service Title,Title Classification,Title Code No,Level,Job Category,Full-Time/Part-Time indicator,Career Level,...,Preferred Skills,Additional Information,To Apply,Hours/Shift,Work Location 1,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
count,2376,2376,2376,2376,2376,2376,2376,2376,2376,2376,...,1273,732,1003,300,2376,2376,2376,2327,2376,2376
unique,59,2,927,295,6,313,18,103,2,5,...,593,235,308,69,204,50,79,73,69,1
top,DEPT OF HEALTH/MENTAL HYGIENE,External,ASSISTANT PROJECT MANAGER,COMMUNITY COORDINATOR,Competitive-1,56058,00,"Engineering, Architecture, & Planning",F,Experienced (non-manager),...,"•\tComputer literate (MS Word, Excel & Outlook...","In addition, the NYC Department of Consumer an...","Click the ""Apply"" button.",35 Hours Per Week,30-30 Thomson Ave L I City Qns,New York City residency is generally required ...,07/09/2026,31-JUL-2026,07/09/2026,07/20/2026
freq,459,1230,26,183,1375,183,931,341,2293,1756,...,11,32,106,26,201,1259,133,105,172,2376

In [32]:
# Verify how many rows are part of duplicate records
duplicates.shape

(28, 30)

In [33]:
# Remove exact duplicate rows to improve data quality
jobs = jobs.drop_duplicates()

In [34]:
jobs.shape

(2362, 30)

In [35]:
# Remove the Recruitment Contact column because it contains only missing values
jobs = jobs.drop(columns=["Recruitment Contact"])

In [36]:
jobs.shape

(2362, 29)

In [ ]:
# Export the cleaned dataset for SQL analysis
jobs.to_csv("Jobs_NYC_Postings_Cleaned.csv", index=False)

In [40]:
cleaned_jobs = pd.read_csv("Jobs_NYC_Postings_Cleaned.csv")
cleaned_jobs.head()

,Job ID,Agency,Posting Type,# Of Positions,Business Title,Civil Service Title,Title Classification,Title Code No,Level,Job Category,...,Preferred Skills,Additional Information,To Apply,Hours/Shift,Work Location 1,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
0,780282,DISTRICT ATTORNEY RICHMOND COU,Internal,1,Victim Advocate,COMMUNITY ASSOCIATE,Non-Competitive-5,56057,00,Social Services,...,• Master’s or bachelor’s degree in social work...,NaN,TO APPLY: ALL APPLICATIONS MUST BE SUBMITTED T...,NaN,"130 Stuyvesant Place, S.I.",New York City residency is generally required ...,07/10/2026,08-SEP-2026,07/10/2026,07/20/2026
1,786162,OFFICE OF CRIMINAL JUSTICE,External,1,"Lead Researcher, Behavioral Health",RESEARCH PROJECTS COOR(MA)-MGR,Pending Classification-2,0527A,M1,"Technology, Data & Innovation",...,"The successful candidate must be curious, flex...",NaN,NaN,NaN,"1 Centre St., N.Y.",New York City residency is generally required ...,07/14/2026,12-SEP-2026,07/15/2026,07/20/2026
2,783706,POLICE DEPARTMENT,External,1,"Instructor, Civilian Development Unit",ADM MANAGER-NON-MGRL FRM M1/M2,Competitive-1,1002C,01,"Policy, Research & Analysis",...,Candidates should have above average experienc...,All instructors in the NYPD Police Academy mus...,"Click the ‘Apply’ Button below, or visit: http...","Day Tours: Monday Through Friday, Saturday and...",130-30 28th Ave,New York City residency is generally required ...,06/22/2026,22-JUL-2026,07/09/2026,07/20/2026
3,782778,CONSUMER AND WORKER PROTECTION,External,2,Litigation Supervisor - Worker Protection,EXECUTIVE AGENCY COUNSEL,Non-Competitive-5,95005,M5,Legal Affairs,...,"•\tAt least 10 years of legal experience, incl...","In addition, the NYC Department of Consumer an...","To apply for this position, please submit your...",NaN,"42 Broadway, N.Y.",New York City Residency is not required for th...,06/08/2026,07-AUG-2026,06/08/2026,07/20/2026
4,786621,CONSUMER AND WORKER PROTECTION,External,1,Business Analyst / Project Manager,COMPUTER SYSTEMS MANAGER,Competitive-1,1005D,00,"Technology, Data & Innovation",...,•\tStrong working knowledge of business proces...,"In addition, the NYC Department of Consumer an...","To apply for this position, please submit your...",NaN,"42 Broadway, N.Y.",New York City Residency is not required for th...,07/16/2026,14-SEP-2026,07/17/2026,07/20/2026